#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
picom --experimental-backend &
dunst &
$HOME/.config/polybar/launch.sh
."${HOME}/.cache/wal/colors.sh"
#wallpaper="$(ls-1A~/Pictures/wallpapers/ | shuf -n 1)";feh --bg-fill $wallpaper; wal -i $wallpaper -n
#wallpaper="~/Pictures/wallpapers/15.png;feh --bg-fill $wallpaper;wall -i $wallpaper -n"

#xidlehook --not-when-fullscreen --not-when-audio --timer 600 'systemctl suspend' '' &

bspc monitor -d I II III IV V VI VII VIII

#### BSPWM configuration ####
bspc config border_radius                 10
bspc config border_width                  3
bspc config window_gap                    8
bspc config top_padding                   40
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#set pywal for bspwm color scheme
bspc config normal_border_color "$color5"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

#rules for apps to startup
bspc rule -a KeePass desktop=^8
bspc rule -a Spotify desktop=^7

#start pywal and restore wallpaper
~/walstart.sh
