#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
picom -b --experimental-backend -b &
dunst &
$HOME/.config/polybar/launch.sh
."${HOME}/.cache/wal/colors.sh"
sh ~/.scripts/wallpaper.sh &
wallpaper="$(ls-1A~/Pictures/wallpapers/ | shuf -n 1)";feh --bg-scale $wallpaper; wal -i $wallpaper -n
#exec --no-startup-id xidlehook --timer 300 "brightnessctl set 600" "brightnessctl set 1500" exec --no-startup-id xidlehook --not-when-audio --timer 360 "betterlockscreen -l dim" ''

bspc monitor -d I II III IV V VI

#### BSPWM configuration ####
bspc config border_radius                 10
bspc config border_width                  1
bspc config window_gap                    8
bspc config top_padding                   40
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#set pywal for bspwm color scheme
bspc config normal_border_color "$color4"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#start pywal and restore wallpaper
~/walstart.sh
