#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backend &
#dunst &
$HOME/.config/polybar/launch.sh
."${HOME}/.cache/wal/colors.sh"
#wal -i ~/Pictures/wallpapers/
wallpaper="$(ls-1A~/Pictures/wallpapers/ | shuf -n 1)";feh --bg-center $wallpaper; wal -i $wallpaper -n

bspc monitor -d I II III IV V VI

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#set pywal for bspwm color scheme
bspc config normal_border_color "$color4"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#start pywal and restore wallpaper
~/walstart.sh
